### ISSUE TITLE
Scheduling is off

### ISSUE THREAD

**Issue by doramelindatunde** [cornucopia-machines/ugly-duckling-firmware#176]
Original report from user:

> tegnap este elinditottam 30pre a dudot es nem zart vissza, folyt egesz ejszaka

**Comment by lptr** [comment]
Fixed by #180 

The scheduling was off by 25032 seconds (a bit less than 7 hours). This was happening across different devices.

My original thought was that somehow NTP got out of sync or something else threw the clock on the devices off. However, the clock was perfectly aligned on all of them.

What _did_ fix things was to drop doing any calculations in `ticks` and keep all calculations in regular time units. The latter are handled as `int64_t`, while `ticks` are `uint32_t`. I'm not sure if it was about converting between them, or something about the unsigned nature of `ticks`, but the switch has fixed things. Damn "undefined behavior" of C++ I guess.
